repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: env\\Scripts\\mypy.exe
        language: system
        types: [python]
        files: ^core/
        pass_filenames: false
        args: [core/]
